###GET ALL POSTINGAN

GET http://localhost:3000/posts
Content-Type: "application/json"

###GET POSTINGAN by ID
GET http://localhost:3000/posts/2
Content-Type: "application/json"

###Create POSTINGAN
POST http://localhost:3000/posts
Content-Type: "application/json"

{
            "judul": "Pemanfaatan Supabase",
            "body": "Supabase berfungsi sebagai alternatif open-source untuk Firebase yang menawarkan backend instan.",
            "created_at": "2024/08/29",
            "image" :"https://picsum.photos/seed/9/200"
}

###UPDATE POSTS by ID
PUT http://localhost:3000/posts/2
Content-Type: "application/json"

{
      "judul": "Tips Tailwind CSS Terbaru COKK",
      "body": "Tailwind CSS adalah framework utility-first yang memudahkan styling komponen.",
      "created_at": "2024/08/28",
      "image": "https://picsum.photos/seed/2/200"
}

###DELETE POSTS by ID
DELETE http://localhost:3000/posts/1
Content-Type: "application/json"